#!/usr/bin/env python3
#
# Satisfiability modulo wordle: solving that annoying game for you, once and
# for all.
#
# Usage:
# $ python3 -m venv ./venv
# $ source ./venv/bin/activate
# (venv) $ pip install z3-solver
# (venv) $ python surdle.py

import argparse
import logging
import sys
import z3

from typing import List

solver = z3.Solver()
letters = z3.Ints('l1 l2 l3 l4 l5')

def parse_args(argv: List[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Wordle cheater",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    ivyp = parser.add_argument_group("Parameters")
    ivyp.add_argument("-d", "--dictfile",
            help="The path to a newline-separated file of English words.",
            default="/usr/share/dict/words")
    ivyp.add_argument("-v", "--verbose",
            help="Dump more info.  More 'v's ==> more info.",
            action='count', default=0)
    args = parser.parse_args(argv)
    init_logging(args)

    return args

def init_logging(args: argparse.Namespace):
    if args.verbose == 0:
        l = logging.WARNING
    if args.verbose == 1:
        l = logging.INFO
    elif args.verbose >= 2:
        l = logging.DEBUG
    else:
        raise Exception(f"Unxpected verbosity level {args.verbose}")
    logging.basicConfig(format='surdle:%(levelname)s:%(message)s', level=l)

def encode_char(i: int, c: str) -> z3.ExprRef:
    assert(len(c) == 1)
    assert(c.islower())
    return letters[i] == ord(c)

def encode(s: str) -> List[z3.ExprRef]:
    assert(len(s) == 5)
    return [encode_char(i,c) for i,c in enumerate(s)]

def decode(l: List[z3.ExprRef]) -> str:
    ords: List[int] = [l[letters[i]].as_long() for i in range(len(l))]
    s = "".join([chr(i) for i in ords])

    assert(len(s) == 5)
    assert(s.islower())
    return s

def domain_constraints() -> z3.And:
    """ Adds a conjunction constraining the range of all letters. """
    return z3.And([
        z3.And([l >= ord('a'),
                l <= ord('z')]) for l in letters])

def dictionary_constraints(fn: str) -> z3.Or:
    """Adds a disjunction of five-letter English words."""

    constraints: List[z3.And] = []
    with open(fn) as f:
        logging.debug(f"Reading dictionary at {fn}...")
        for line in f:
            line = line.lower().strip()
            if len(line) != 5:
                continue
            constraints.append(z3.And(*encode(line)))
        logging.info(f"Added {len(constraints)} dictionary constraints.")
    return z3.Or(*constraints)

def green_constraint(i: int, c: str) -> z3.ExprRef:
    """ Encodes the fact that letter i is exactly c. """
    logging.debug(f"Remembering that letter {i} is {c}")
    return letters[i] == ord(c)

def yellow_constraint(i: int, c: str) -> z3.ExprRef:
    """" Encodes the fact that c is in the word but not at position i."""
    constraints = []
    candidates = []
    for j in range(len(letters)):
        if j != i:
            candidates.append(j)
            constraints.append(letters[j] == ord(c))
    logging.debug(f"Remembering that letter {i} is not {c}")
    logging.debug(f"Remembering that more or more of {candidates} is {c}")
    return z3.And(
            letters[i] != ord(c),
            z3.Or(*constraints))

def black_constraint(i: int, c: str) -> z3.ExprRef:
    """ Encodes the fact that c is nowhere in the word."""
    logging.debug(f"Remembering that no letter is {c}")
    constraints = [letters[j] != ord(c) for j in range(5)]
    return z3.And(*constraints)

def main(argv: List[str]) -> int:
    args = parse_args(argv[1:])
    solver.add(domain_constraints())
    solver.add(dictionary_constraints(args.dictfile))

    action_table = {
        '⬛': black_constraint,
        '🟨': yellow_constraint,
        '🟩': green_constraint,
        'b': black_constraint,
        'y': yellow_constraint,
        'g': green_constraint
    }

    while True:
        logging.info("Solving...")
        sat = solver.check()

        if sat == z3.sat:
            m = solver.model()
            guess = decode(m)
            print(f"Guessing {guess}")

            # Check for unique solutions
            solver.add(z3.Not(z3.And(*encode(guess))))
            sat = solver.check()
            if sat != z3.sat:
                print("Unique!")
                return 0
        else:
            print(solver.unsat_core())
            return 1

        while True:
            feedback = input("> ").strip()
            valid = [c in "🟩🟨⬛gyb" for c in feedback]
            if len(feedback) == 5 and all(valid):
                break
        for i, c in enumerate(feedback):
            solver.add(action_table[c](i,guess[i]))

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
